theme: minima
title: Josh Platzman
author: Josh Platzman
email: jplatzman@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 I tell you a little about my self, including my accomplishments, my goals, and my hobbies.

# social links
twitter_username: JPlatzman # DO NOT include the @ character, or else the build will fail!
github_username:  joshplatzman # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
